package org.example;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import java.util.*;

public class signInPage{
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
        driver.get("https://www.trendyol.com/");
        driver.manage().window().setSize(new Dimension(1920, 1080));
    }
    @After
    public void tearDown() {
        try {
            Thread.sleep(1000);
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
       driver.quit();
    }

    @Test
    public void signInNoLetter() {

        if (!driver.findElements(By.className("homepage-popup-img")).isEmpty()) {
            driver.findElement(By.className("homepage-popup-img")).click();
        }

        {
            driver.findElement(By.cssSelector("div[class='link account-user'] p[class='link-text']")).click();

        }

        {
            WebElement element = driver.findElement(By.cssSelector(".q-secondary:nth-child(2)"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        driver.findElement(By.cssSelector(".q-secondary:nth-child(2)")).click();
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        driver.findElement(By.id("register-email")).click();
        driver.findElement(By.id("register-email")).sendKeys("javatest61@gmail.com");
        driver.findElement(By.id("register-password-input")).click();
        driver.findElement(By.id("register-password-input")).sendKeys("123456789123"); // no letter password
        driver.findElement(By.id("register-password-input")).sendKeys(Keys.ENTER);

        if (!driver.findElements(By.id("error-box-wrapper")).isEmpty()) {
            assert(true);
        }
        else assert(false);

    }
    @Test
    public void signInNoNumber() {



        if (!driver.findElements(By.className("homepage-popup-img")).isEmpty()) {
            driver.findElement(By.className("homepage-popup-img")).click();
        }

        {
            driver.findElement(By.cssSelector("div[class='link account-user'] p[class='link-text']")).click();

        }

        {
            WebElement element = driver.findElement(By.cssSelector(".q-secondary:nth-child(2)"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        driver.findElement(By.cssSelector(".q-secondary:nth-child(2)")).click();
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        driver.findElement(By.id("register-email")).click();
        driver.findElement(By.id("register-email")).sendKeys("javatest61@gmail.com");
        driver.findElement(By.id("register-password-input")).click();
        driver.findElement(By.id("register-password-input")).sendKeys("Javatesting"); // no number password
        driver.findElement(By.id("register-password-input")).sendKeys(Keys.ENTER);




        if (!driver.findElements(By.id("error-box-wrapper")).isEmpty()) {
            assert(true);
        }
        else assert(false);

    }

    @Test
    public void signInNoUpperCase() {

        if (!driver.findElements(By.className("homepage-popup-img")).isEmpty()) {
            driver.findElement(By.className("homepage-popup-img")).click();
        }

        {
            driver.findElement(By.cssSelector("div[class='link account-user'] p[class='link-text']")).click();

        }

        {
            WebElement element = driver.findElement(By.cssSelector(".q-secondary:nth-child(2)"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        driver.findElement(By.cssSelector(".q-secondary:nth-child(2)")).click();
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        driver.findElement(By.id("register-email")).click();
        driver.findElement(By.id("register-email")).sendKeys("javatest61@gmail.com");
        driver.findElement(By.id("register-password-input")).click();
        driver.findElement(By.id("register-password-input")).sendKeys("javatesting01"); // no upper case letter password
        driver.findElement(By.id("register-password-input")).sendKeys(Keys.ENTER);

        if (!driver.findElements(By.id("error-box-wrapper")).isEmpty()) {
            assert(true);
        }
        else assert(false);

        //this is an error, doesn't meet the requirements of upper case
    }

    @Test
    public void signInTrue() {
        driver.get("https://www.trendyol.com/");
        driver.manage().window().setSize(new Dimension(1066, 856));


        if (!driver.findElements(By.className("homepage-popup-img")).isEmpty()) {
            driver.findElement(By.className("homepage-popup-img")).click();
        }

        {
            driver.findElement(By.cssSelector("div[class='link account-user'] p[class='link-text']")).click();

        }

        {
            WebElement element = driver.findElement(By.cssSelector(".q-secondary:nth-child(2)"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        driver.findElement(By.cssSelector(".q-secondary:nth-child(2)")).click();
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        driver.findElement(By.id("register-email")).click();
        driver.findElement(By.id("register-email")).sendKeys("javatest61@gmail.com");
        driver.findElement(By.id("register-password-input")).click();
        driver.findElement(By.id("register-password-input")).sendKeys("Javatesting01");
        driver.findElement(By.id("register-password-input")).sendKeys(Keys.ENTER);


        if (!driver.findElements(By.id("error-box-wrapper")).isEmpty()) {
            assert(false);
        }
        else assert(true);

    }


}

